### ISSUE TITLE
Add classes to HTML instead of the BODY

### ISSUE THREAD

**Issue by fcisio** [codeAdrian/gatsby-omni-font-loader#13]
Hi, would it be possible to add the loaded classes on HTML instead of the Body?
This would allow setting styles at the root of the project instead of its first child.

I bring up this use case mainly because of `rem` units, which are relative to the font-size at the root.
So if you have the intention of using `rem` units anywhere, the font-size needs to be on HTML tag.

This could potentially be a new option `scope: 'html/body'`, preventing breaking changes.

**Comment by codeAdrian** [comment]
Hi @fcisio , thanks for reaching out. I like the idea and I'll make sure to implement the option and release the new version tomorrow. Class names will be attached to the `body` by default, with a new option to change it to an `html` element.

**Comment by fcisio** [comment]
Hey @codeAdrian ,
I didn't see your answer and I went ahead with a PR.

I'm pitching pretty big changes, let me know what you think!
Thanks.

**Comment by codeAdrian** [comment]
I'm closing this issue since we merged the PR
