### ISSUE TITLE
Error: Failed to decode downloaded font: <URL>  

### ISSUE THREAD

**Issue by abdullahe** [codeAdrian/gatsby-omni-font-loader#2]
Hi Adrian,

I am getting this error in console, when I try to use the plugin. The fonts don't show but the bundle is developed, and site works.

Here is my folder structure:

```
├───src     
│   ├───components
│   │       all.sass
└───static
    ├───fonts
    │       local_fonts.css
    │       montserrat-latin-ext-400-italic.woff
    │       montserrat-latin-ext-400-italic.woff2
    │       montserrat-latin-ext-400-normal.woff
    │       montserrat-latin-ext-400-normal.woff2
```
local_fonts.css:

```
@font-face {
  font-family: "Montserrat";
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url("/montserrat-latin-ext-400-normal.woff2") format("woff2"),
    url("/montserrat-all-400-normal.woff") format("woff");
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB,
    U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}

@font-face {
  font-family: "Montserrat";
  font-style: italic;
  font-display: swap;
  font-weight: 400;
  src: url("/montserrat-latin-ext-400-italic.woff2") format("woff2"),
    url("/montserrat-all-400-italic.woff") format("woff");
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB,
    U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
```

imported to all.sass like this:

`@import "../../static/fonts/local_fonts.css"
`

gatsby-config.js:

```
    {
      /* Include plugin */
      resolve: "gatsby-omni-font-loader",

      /* Plugin options */
      options: {
        /* Enable font loading listener to handle FOUC */
        enableListener: true,

        /* Self-hosted fonts config. Add font files and font CSS files to "static" folder */
        custom: [
          {
            /* Exact name of the font as defied in @font-face CSS rule */
            name: ["Montserrat"],
            /* Path to the font CSS file inside the "static" folder with @font-face definition */
            file: "/fonts/local_fonts.css",
          },
        ],
      },
    }
```

This is probably my mistake because I am new to all this. Any tips would be appreciated.

Thanks.

**Comment by codeAdrian** [comment]
Hello, thanks for reaching out.

Issue is related with how you defined the path to the font file in your `local_fonts.css` file:

```
url("/montserrat-all-400-normal.woff")
```

This path points to the website root. It should be changed to `url("/fonts/montserrat-all-400-normal.woff")` or `url("./montserrat-all-400-normal.woff")`

**Comment by abdullahe** [comment]
Thanks for the reply!

I did the change, the error disappeared however font is not shown.

I can see the body as `<body class="wf-montserrat--loaded wf-playfair-display--loaded" data-react-helmet="class">` and see this in the under head: `<link rel="preload" as="style" href="/fonts/local_fonts.css">`

**Comment by codeAdrian** [comment]
Have you set the font in CSS to be Montserrat?

```
.wf-montserrat--loaded {
  font-family: "Montserrat";
}
```

**Comment by codeAdrian** [comment]
<img width="237" alt="Screenshot 2020-11-09 at 15 04 17" src="https://user-images.githubusercontent.com/11479290/98550810-d8a70880-229c-11eb-90e7-265ed69aef01.png">

This is how it should look like in `public` folder. You can run `yarn clean && yarn develop` to regenerate static content.

**Comment by abdullahe** [comment]
No, I didn't set the font in CSS separately because I use Bulma and here is how I defined them as variables:

```
$family-primary: "Montserrat"
$family-secondary: "Playfair Display"
```

and use like:
`<p className="is-family-secondary">
`
which adds this to the element:
```
.is-family-secondary {
    font-family: "Playfair Display" !important;
}
```

Fonts are visible in public folder:
![image](https://user-images.githubusercontent.com/699010/98551133-06e11400-22ae-11eb-930a-e366f05e70f8.png)


Not sure what I can try. Thanks for your time.

**Comment by codeAdrian** [comment]
This is now outside the realm of the plugin, I'm afraid. If the fonts are loaded properly and CSS classes are added to the body, that means that fonts are available in the browser and loaded. 

 So the rest is up to your CSS definition. Good luck!
