### ISSUE TITLE
tag[primaryAttributeKey].toLowerCase is not a function

### ISSUE THREAD

**Issue by jonoroboto** [codeAdrian/gatsby-omni-font-loader#6]
First of all, let me start by saying, we saw your original reddit post for this particular Gatsby plugin and read your blog post. We're blown away with the functionality and plan to use it in nearly every one of our sites. That being said...

We've encountered this issue twice, [once on this site](https://roboto.studio/ ) and [once here](https://interrobangstudio.netlify.app/). We'd love to try and get to the bottom of it, and I suspect it's related to [this issue](https://github.com/nfl/react-helmet/issues/448).

See screenshot:
<img width="1279" alt="Screenshot 2020-12-01 at 12 09 07" src="https://user-images.githubusercontent.com/29231011/100738782-054acd80-33ce-11eb-9b65-edd24330955a.png">

**Comment by codeAdrian** [comment]
Hi @jonoroboto , thanks for the kind words. I'm glad to hear that you plan on using it on your projects.

Can you provide me with the `gatsby-config.js` and `package.json` so I can check what is going on under the hood? Also, does this issue happen right after you've installed my plugin, are there any special steps to reproduce it? Additionally, have you tried removing node_modules, yarn.lock, running `yarn clean` and reinstalling the packages?

**Comment by jonoroboto** [comment]
Just a quick update - looking at this right now, but having an issue with emotion moving the core package naming. Will be on this for as long as it takes, appreciate the swift response.

**Comment by codeAdrian** [comment]
@jonoroboto I've ran some of the test cases on a newest version of Gatsby, but I couldn't reproduce the issue. From the stack trace you've attached, It seems like the issue is completely internal within the Helmet package, as it doesn't link to the any code from the font plugin or your `src` code. So I'm not sure what is going on.

As I can see from the websites attached (they look great, by the way) I can see that the plugin works well here https://roboto.studio/

In any case, I'll need more detail to properly trace the issue, if it is related to the plugin. In any case, keep me posted. You can fork and clone the plugin repo into `project-root/plugins` folder and run the plugin locally to debug it. If you manage to fix the issue, feel free to submit a PR.

**Comment by jonoroboto** [comment]
Ok update - I think this might be the issue. It could be due to the way they've changed naming convention in the latest emotion update. We're using the same package, and it broke a bunch of our stuff
![image](https://user-images.githubusercontent.com/29231011/100743707-96bd3e00-33d4-11eb-91a1-39dec0737cd2.png)

**Comment by jonoroboto** [comment]
Full sized screenshot

<img width="1279" alt="Screenshot 2020-12-01 at 12 57 07" src="https://user-images.githubusercontent.com/29231011/100743801-b94f5700-33d4-11eb-924d-46ef12a607bc.png">

**Comment by codeAdrian** [comment]
Yeah, I had to deal with that issue few days ago. Quick tip regarding the emotion issue:

You'll need to use the beta version of `gatsby-plugin-emotion` until they release the next version. 5.1. will support Emotion 11. Or you can just downgrade emotion back to latest version 10.

```
 "gatsby-plugin-emotion": "^5.1.0-next.0",
```

Let me know if I can close the issue. Cheers!

**Comment by codeAdrian** [comment]
@jonoroboto Weird that the emotion error is relating it to my plugin, as it is not using Emotion all all. All styles are just regular React inline styles.

```
  const hiddenStyles: React.CSSProperties = {
    position: "absolute",
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    height: "1px",
    width: "1px",
    margin: "-1px",
    padding: "0",
    border: "0",
  }
```

I think that when you upgrade it to version 11, the issue will just go away. Maybe it's just detecting all CSS as error, including that of my plugin.

**Comment by jonoroboto** [comment]
No probs Adrian, really appreciate the help.

I'm going to close the issue for now, as there's a lot more going wrong than just the omni font loader, that's completely on my side. Thanks again, will give you an update when this is fixed up 👍

**Comment by codeAdrian** [comment]
@jonoroboto Thank you. I checked everything with Emotion 11. Everything works as expected. No build errors occur with Emotion 11. I am attaching a working config and screenshots.

Package.json
```
    "@emotion/react": "^11.1.1",
    "gatsby-plugin-emotion": "5.1.0-next.0",
    "gatsby-omni-font-loader": "^1.1.1",
```

gatsby-browser.js
```
  `gatsby-plugin-emotion`,
    {
      resolve: "gatsby-omni-font-loader",
      options: {
        enableListener: true,
        preconnect: [
          "https://fonts.gstatic.com"
        ],
        web: [
          {
            name: "Henny Penny",
            file:
              "https://fonts.googleapis.com/css2?family=Henny+Penny&display=swap",
          },
          {
            name: "Roboto",
            file:
              "https://fonts.googleapis.com/css2?family=Roboto&display=swap",
          },
        ],
      },
    },
```

<img width="595" alt="Screenshot 2020-12-01 at 14 12 56" src="https://user-images.githubusercontent.com/11479290/100745264-50211100-33df-11eb-94d1-5d868f90cc50.png">

<img width="592" alt="Screenshot 2020-12-01 at 14 13 20" src="https://user-images.githubusercontent.com/11479290/100745303-5f07c380-33df-11eb-9561-cc93fa4698ca.png">
